-- drop database airman;
-- create database airman;
-- use airman;

DROP TABLE IF EXISTS flight;
DROP TABLE IF EXISTS airplane;
DROP TABLE IF EXISTS company;

create table if not exists company
(
	id bigint generated by default as identity
		constraint company_pkey
			primary key,
	created timestamp(0),
	name varchar(255) not null,
	updated timestamp(0),
	version integer default 0,
	founded date,
	type integer not null
);

alter table company owner to postgres;



create table if not exists airplane
(
	id bigint generated by default as identity
		constraint airplane_pkey
			primary key,
	created timestamp(0),
	name varchar(255) not null,
	updated timestamp(0),
	version integer default 0,
	flight_distance integer not null,
	fuel_capacity integer not null,
	number_of_flights integer not null,
	plane_created date,
	serial integer not null,
	type integer not null,
	company_id bigint
		constraint fkoa6shv8ijts0xqvebffyqj16b
			references company
);

alter table airplane owner to postgres;



create table if not exists flight
(
	id bigint generated by default as identity
		constraint flight_pkey
			primary key,
	created timestamp(0),
	name varchar(255) not null,
	updated timestamp(0),
	version integer default 0,
	delay_started_date_time timestamp with time zone,
	depart_country varchar(255) not null,
	dest_country varchar(255) not null,
	distance integer,
	ended_date_time timestamp with time zone,
	estimated_flight_time time not null,
	started_date_time timestamp with time zone,
	status integer not null,
	airplane_id bigint
		constraint fkb8t4272gfgo1feyyidvscbjm0
			references airplane,
	company_id bigint
		constraint fk1gyrukpctenh75dryrx21vhxy
			references company
);

alter table flight owner to postgres;


